# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!


# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  domain_name: example.com
  secret_key_base: 103b10eff132359219f708601b3c83ebccaaa876573fa8f17558b714756a204d3c36bfdbd4544b1fa025d6bac61bd56ce2e54dc9e09f2cc9361b8540fe8a2139
  client_id: 54488169288-h8tupeo01sfuhvp5q2poiunf4bll1dtg.apps.googleusercontent.com
  client_secret: suMby9OqURRqviCzpZIXOLvh


test:
  secret_key_base: 481a55ce5f538512d8e73a5a0004a473bfd95e0b0b1393296cb38437f233680a5fd4f7c99cb64867001177cf3c4461724ef96c26d0fb160d4e9598ebe79bb27b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  #domain_name: <%= ENV["DOMAIN_NAME"] %>
  #secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

 domain_name: closetcatalyst.net
 secret_key_base:   103b10eff132359219f708601b3c83ebccaaa876573fa8f17558b714756a204d3c36bfdbd4544b1fa025d6bac61bd56ce2e54dc9e09f2cc9361b8540fe8a2139
